[build]
  command = "npm run build:netlify"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "22.13.0"

[[headers]]
  for = "/musica-karina-pablo.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
